# Parameters for prediction
prediction:
  ros__parameters:
    wheel_separation: 0.46
    wheel_radius: 0.1
    time_step: 0.1
    initial_x: 0.0
    initial_y: 0.0
    initial_yaw: 0.0
    initial_linear_vel: 0.0
    initial_angular_vel: 0.0
    odom_frame_id: "odom"
    base_frame_id: "base_link"

# Parameters for measurement
measurement:
  ros__parameters:
    vo_odom_topic: "/vo/odom"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    time_step: 0.1

# Parameters for ekf
ekf:
  ros__parameters:
    odom_frame_id: "odom"
    base_frame_id: "base_link"    
    time_step: 0.1         

# Parameters for test
test:
  ros__parameters:
    odom_frame_id: "odom"
    time_step: 0.1    